var TopLevel = {
"app" : function () {},
"BrowserWindow" : function () {},
"console" : function () {},
"crashReporter" : function () {},
"ctime" : function () {},
"getTime" : function () {},
"ipcMain" : function () {},
"join" : function () {},
"loadURL" : function () {},
"log" : function () {},
"on" : function () {},
"path" : function () {},
"platform" : function () {},
"quit" : function () {},
"readdirSync" : function () {},
"resolve" : function () {},
"send" : function () {},
"start" : function () {},
"stats" : function () {},
"statSync" : function () {},
"Tail" : function () {},
"type" : function () {},
"unwatch" : function () {},
"watch" : function () {}
}